# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_carusel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Carusel(object):
    def setupUi(self, Carusel):
        Carusel.setObjectName("Carusel")
        Carusel.resize(112, 160)
        Carusel.setMinimumSize(QtCore.QSize(112, 0))
        Carusel.setMaximumSize(QtCore.QSize(112, 16777215))
        Carusel.setStyleSheet("#label_info{\n"
"    background-color:#ffbc0d;\n"
"}\n"
"QWidget{\n"
"    background-color:#ffffff;\n"
"}\n"
"\n"
"#frame_4 {\n"
"    font: 7pt;\n"
"    border-style: solid;\n"
"    border-color: #a3a3a3;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Carusel)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(Carusel)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.frame_4)
        self.widget.setMinimumSize(QtCore.QSize(0, 20))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget.setObjectName("widget")
        self.label_info = QtWidgets.QLabel(self.widget)
        self.label_info.setGeometry(QtCore.QRect(0, 0, 56, 12))
        self.label_info.setObjectName("label_info")
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.frame_4)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.item_img = QtWidgets.QLabel(self.widget_2)
        self.item_img.setMinimumSize(QtCore.QSize(80, 80))
        self.item_img.setMaximumSize(QtCore.QSize(80, 80))
        self.item_img.setText("")
        self.item_img.setScaledContents(True)
        self.item_img.setAlignment(QtCore.Qt.AlignCenter)
        self.item_img.setObjectName("item_img")
        self.horizontalLayout.addWidget(self.item_img)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.frame_4)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menu_name = QtWidgets.QLabel(self.widget_3)
        self.menu_name.setObjectName("menu_name")
        self.verticalLayout_3.addWidget(self.menu_name)
        self.menu_price_cal = QtWidgets.QLabel(self.widget_3)
        self.menu_price_cal.setObjectName("menu_price_cal")
        self.verticalLayout_3.addWidget(self.menu_price_cal)
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.frame_4)

        self.retranslateUi(Carusel)
        QtCore.QMetaObject.connectSlotsByName(Carusel)

    def retranslateUi(self, Carusel):
        _translate = QtCore.QCoreApplication.translate
        Carusel.setWindowTitle(_translate("Carusel", "Form"))
        self.label_info.setText(_translate("Carusel", "신제품"))
        self.menu_name.setText(_translate("Carusel", "MenuName"))
        self.menu_price_cal.setText(_translate("Carusel", "MenuPriceAndCal"))
