# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_pay_finish_modal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Modal_finish(object):
    def setupUi(self, Modal_finish):
        Modal_finish.setObjectName("Modal_finish")
        Modal_finish.resize(540, 960)
        Modal_finish.setWindowOpacity(1.0)
        Modal_finish.setStyleSheet("*{\n"
"    font: 28pt \"배달의민족 도현\";\n"
"    color: #292929;\n"
"}\n"
"#widget_main{\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QScrollArea {\n"
"    background: transparent;\n"
"    border-style: none;\n"
"}\n"
"\n"
"QScrollArea * {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"        background: #white;\n"
"        width:20px;\n"
"        margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-radius : 10px;\n"
"    border-color: #a3a3a3;\n"
"    background-color : #ffffff;\n"
"\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border-width:2px;\n"
"    border-style: solid;\n"
"    border-radius : 10px;\n"
"    border-color: #a3a3a3;\n"
"    background-color: white;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color: #a3a3a3;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-radius : 10px;\n"
"    border-color: #a3a3a3;\n"
"    background-color: white;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"    background-color: #a3a3a3;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"    background-color : #ffffff;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-radius : 5px;\n"
"    border-color: #a3a3a3;\n"
"}\n"
"\n"
"QPushButton:Pressed {\n"
"    background-color : #eeeeee;\n"
"}\n"
"\n"
"#btn_add_basket_count,\n"
"#label_info,\n"
"#banner_1,\n"
"#banner_2,\n"
"#banner_3,\n"
"#banner_4\n"
"{\n"
"    background-color: #ffbc0d;\n"
"}\n"
"\n"
"#banner_5{\n"
"    background-color: #dcdcdc;\n"
"}\n"
"\n"
"#banner_1_inner,\n"
"#banner_2_inner,\n"
"#banner_3_inner,\n"
"#banner_4_inner\n"
"{\n"
"    background-color: white;\n"
"}\n"
"\n"
"#widget_left, #widget_right{\n"
"    border-style: solid;\n"
"    border-color: #a3a3a3;\n"
"    border-width: 2px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#frame_big_item_stapper, #pay_way_1, #pay_way_2{\n"
"    border-style: solid;\n"
"    border-color: #a3a3a3;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"\n"
"#label_menu_name {\n"
"    font: 16pt;\n"
"}\n"
"\n"
"#label_ask_set {\n"
"    font: 24pt;\n"
"}\n"
"\n"
"#label_info_set, #label_info_single{\n"
"    font: 14pt;\n"
"}\n"
"\n"
"#btn_cancel {\n"
"    font: 14pt;\n"
"}\n"
"\n"
"#label_ask_pay_way, #label_ask_pay_way_2{\n"
"    font: 26pt;\n"
"}\n"
"\n"
"#label_item_count {\n"
"    border-width : 1px;\n"
"    border-style: solid;\n"
"    border-color: #eeeeee;\n"
"    font: 12pt;\n"
"}\n"
"#btn_plus, #btn_minus{\n"
"    font: 18pt;\n"
"}\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Modal_finish)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_main = QtWidgets.QWidget(Modal_finish)
        self.widget_main.setObjectName("widget_main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_main)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_body_main_3 = QtWidgets.QWidget(self.widget_main)
        self.widget_body_main_3.setObjectName("widget_body_main_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_body_main_3)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 240, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.widget_2 = QtWidgets.QWidget(self.widget_body_main_3)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_logo = QtWidgets.QLabel(self.widget_2)
        self.label_logo.setMinimumSize(QtCore.QSize(250, 250))
        self.label_logo.setMaximumSize(QtCore.QSize(250, 250))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("ui\\../src/logo.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout.addWidget(self.label_logo)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.widget_body_main_3)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.widget_body_main_3)
        self.verticalLayout_2.addWidget(self.widget_main)

        self.retranslateUi(Modal_finish)
        QtCore.QMetaObject.connectSlotsByName(Modal_finish)

    def retranslateUi(self, Modal_finish):
        _translate = QtCore.QCoreApplication.translate
        Modal_finish.setWindowTitle(_translate("Modal_finish", "Form"))
        self.label.setText(_translate("Modal_finish", "감사합니다"))
